og:title: Exam 70-483
title: Exam 70-483
description: Criar e usar tipos
github_username: https://github.com/shyoutarou
theme: jekyll-theme-midnight
google-site-verification: kg50GjPxJzeZrWjVtYbRE5i-xpi7UvYsf753E8JJR4A

