og:title: Exam 70-483
title: Exam 70-483
description: Criar e usar tipos
github_username: https://github.com/shyoutarou
theme: jekyll-theme-midnight
google-site-verification: google0006a0d2df5890fa.html
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
